In [1]:
# np stack / hstack / vstack test

import numpy as np

a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
     [10, 11, 12]]

b = [[[1], [2], [3]],
     [[4], [5], [6]],
     [[7], [8], [9]],
     [[10], [11], [12]]]

c = [[1, 2],
     [3, 4],
     [5, 6],
     [7, 8],
     [9, 10],
     [11, 12]]

d = [[[1], [2]], 
     [[3], [4]],
     [[5], [6]],
     [[7], [8]],
     [[9], [10]],
     [[11], [12]]] 

e = [[[1, 2], [3, 4]],
     [[5, 6], [7, 8]],
     [[9, 10], [11, 12]]]

f = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# print(np.array(a))
# print(np.hstack(a))
# print(np.vstack(a))
# print()
# print(np.array(b))
# print(np.hstack(b))
# print(np.vstack(b))
# print()
# print(np.array(c))
# print(np.hstack(c))
# print(np.vstack(c))
# print()
# print(np.array(d))
# print(np.hstack(d))
# print(np.vstack(d))
# print()
# print(np.array(e))
# print(np.hstack(e))
print(np.vstack(e))
# print()
print(np.array(f))
print(np.hstack(f))
print(np.vstack(f))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [2]:
# sklearn-shuffle test
from sklearn.utils import shuffle

X = np.vstack(np.arange(10))
y = np.arange(10, 20)
print(X, y)
X, y = shuffle(X, y, random_state=42)
print(X, y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] [10 11 12 13 14 15 16 17 18 19]
[[8]
 [1]
 [5]
 [0]
 [7]
 [2]
 [9]
 [4]
 [3]
 [6]] [18 11 15 10 17 12 19 14 13 16]
